version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: beachunirv_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beachunirv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  pgdata:

networks:
  db-network:
    driver: bridge